---
title: "Bagging with Iris Data"
author: "Park Jeong Jin"
date: "2019년 2월 12일"
output: html_document
---
#Data Import

```{r}
iris = read.csv("iris.csv",header=T) 
iris$variety = as.factor(iris$variety)
```

##필요한 패키지 불러오기.
```{r}
library(rpart)
library(adabag)
```

#Model Fitting
##Grow a tree
```{r}
my.control = rpart.control(xval=0, cp=0, minsplit=5, maxdepth=10)
#적어도 5개의 분할을 가지며, 최대 10 깊이의 decision tree 생성.
fit = bagging(variety~., data=iris, mfinal=50, control=my.control)

#각 변수의 중요도를 나타내어줌.
print(fit$importance)
importanceplot(fit)
```

##Prediction & Error
```{r}
# Prediction

pred = predict.bagging(fit, newdata=iris)

ctable = table(iris$variety, pred$class, dnn=c("Actual", "Predicted")); ctable #classification table


# Errors

miss.err = 1-sum(diag(ctable))/sum(ctable); miss.err # Misclassification Rate
pred.acc = 1 - miss.err; pred.acc #Prediction Accuracy
```

#Computing the test error by paritioning

## Data partition
```{r}
V = 2
n =  nrow(iris)
id = sample(1:V, n, prob = c(0.7,0.3), replace = T) # Partitioning 7:3
ii = which(id==1)
iris.train = iris[ii,]
iris.test  = iris[-ii,]
```

## Grow trees

```{r}
set.seed(1234)
my.control = rpart.control(xval=0, cp=0, minsplit=5, maxdepth=10)
fit = bagging(variety~., data=iris.train, mfinal=50, control=my.control)

print(fit$importance)
importanceplot(fit)
```

## Preidiction & Errors

```{r}
#Prediction

pred = predict.bagging(fit, newdata=iris.test)
ctable = table(iris.test$variety, pred$class, dnn=c("Actual", "Predicted")); ctable #classification table


#Errors

miss.err = 1-sum(diag(ctable))/sum(ctable); miss.err # Misclassification Rate
pred.acc = 1 - miss.err; pred.acc #Prediction Accuracy
```

# 10-fold Cross Validation
## Data Set 10개로 분할.
```{r}

V = 10 #V-fold CV
miss.err.train = 0
miss.err.test = 0
set.seed(12345)
id = sample(1:V, nrow(iris), replace = T)
```

## For문을 통하여 각 구간별 error 구함.
```{r}
for(i in 1:V) {
  
  #print(i) <- 각 구간에 잘 작동 중인지 확인하는 장치
  iris.train = iris[id != i,] 
  iris.test = iris[id == i,] 
  
  my.control = rpart.control(xval=0, cp=0, minsplit=5, maxdepth=10)
  fit = bagging(variety~., data=iris.train, mfinal=50, control=my.control)

  pred = predict.bagging(fit, newdata=iris.train)
  ctable = table(iris.train$variety, pred$class, dnn=c("Actual", "Predicted"))
  miss.err.train.temp = 1-sum(diag(ctable))/sum(ctable)
  miss.err.train = miss.err.train + miss.err.train.temp
  
  pred = predict.bagging(fit, newdata=iris.test)
  ctable = table(iris.test$variety, pred$class, dnn=c("Actual", "Predicted"))
  miss.err.test.temp = 1-sum(diag(ctable))/sum(ctable)
  miss.err.test = miss.err.test + miss.err.test.temp
  
}
```

## 최종 CV error
```{r}
cv.err.train = miss.err.train/ V; cv.err.train # CV training error
cv.err.test = miss.err.test/ V;cv.err.test # CV test error
```
